/* ---------------------------------------------------------------------------
 * Mock referral records (Phase D) for UI development.
 *
 * Static, illustrative rows shaped exactly like buildReferralRecord() output so
 * the read-only /referrals table can be built and reviewed before a live
 * "Smoovely Referrals" data source is wired in. NOT real data. Timestamps are
 * hard-coded (no Date.now) so the module stays pure and deterministic.
 * ------------------------------------------------------------------------- */

export const MOCK_REFERRALS = [
  {
    timestamp: "2026-07-20T09:12:00.000Z",
    leadName: "Amara Okafor",
    leadEmail: "amara.okafor@example.com",
    leadPhone: "07700 900101",
    nextMoveType: "Looking to buy",
    targetArea: "Manchester, M20",
    partner: "Estate Agent",
    referralType: "Buyer Lead",
    status: "Viewing Booked",
    revenue: 0,
    referralFee: 0,
    notes: "Keen buyer, pre-approved. Viewing arranged for Saturday.",
    source: "whats-next-opportunity",
  },
  {
    timestamp: "2026-07-20T09:12:00.000Z",
    leadName: "Amara Okafor",
    leadEmail: "amara.okafor@example.com",
    leadPhone: "07700 900101",
    nextMoveType: "Looking to buy",
    targetArea: "Manchester, M20",
    partner: "Mortgage Broker",
    referralType: "Mortgage Lead",
    status: "Contacted",
    revenue: 0,
    referralFee: 0,
    notes: "Broker reaching out re: fixed-rate options.",
    source: "whats-next-opportunity",
  },
  {
    timestamp: "2026-07-18T14:40:00.000Z",
    leadName: "Tom Bexley",
    leadEmail: "tom.bexley@example.com",
    leadPhone: "07700 900110",
    nextMoveType: "Looking to rent",
    targetArea: "Leeds, LS6",
    partner: "Letting Agent",
    referralType: "Rental Lead",
    status: "Converted",
    revenue: 1200,
    referralFee: 120,
    notes: "Tenancy signed. Referral fee invoiced.",
    source: "whats-next-opportunity",
  },
  {
    timestamp: "2026-07-15T11:05:00.000Z",
    leadName: "Priya Nair",
    leadEmail: "priya.nair@example.com",
    leadPhone: "07700 900122",
    nextMoveType: "Property investor",
    targetArea: "Birmingham, B1",
    partner: "Solicitor",
    referralType: "Solicitor Lead",
    status: "Qualified",
    revenue: 0,
    referralFee: 0,
    notes: "Conveyancing quote issued; awaiting instruction.",
    source: "whats-next-opportunity",
  },
  {
    timestamp: "2026-07-14T16:22:00.000Z",
    leadName: "Daniel Hart",
    leadEmail: "daniel.hart@example.com",
    leadPhone: "07700 900133",
    nextMoveType: "Relocating for work",
    targetArea: "London, SW1",
    partner: "Storage Provider",
    referralType: "Storage Lead",
    status: "Sent",
    revenue: 0,
    referralFee: 0,
    notes: "Needs 6 weeks of storage between contracts.",
    source: "whats-next-opportunity",
  },
  {
    timestamp: "2026-07-10T08:30:00.000Z",
    leadName: "Sofia Marín",
    leadEmail: "sofia.marin@example.com",
    leadPhone: "07700 900144",
    nextMoveType: "Student accommodation",
    targetArea: "Bristol, BS8",
    partner: "Letting Agent",
    referralType: "Student Lead",
    status: "Lost",
    revenue: 0,
    referralFee: 0,
    notes: "Found accommodation independently.",
    source: "whats-next-opportunity",
  },
  {
    timestamp: "2026-07-08T13:15:00.000Z",
    leadName: "George Whitlock",
    leadEmail: "george.whitlock@example.com",
    leadPhone: "07700 900155",
    nextMoveType: "Looking to buy",
    targetArea: "Nottingham, NG1",
    partner: "House Clearance",
    referralType: "House Clearance Lead",
    status: "Converted",
    revenue: 480,
    referralFee: 48,
    notes: "Probate clearance completed.",
    source: "whats-next-opportunity",
  },
  {
    timestamp: "2026-07-05T10:00:00.000Z",
    leadName: "Yara Haddad",
    leadEmail: "yara.haddad@example.com",
    leadPhone: "07700 900166",
    nextMoveType: "Looking to rent",
    targetArea: "Glasgow, G1",
    partner: "Utilities Partner",
    referralType: "Utilities Lead",
    status: "New",
    revenue: 0,
    referralFee: 0,
    notes: "",
    source: "whats-next-opportunity",
  },
];
